info:
  build:
    name: Swagger Aggregator
    description: Swagger Aggregator
    version: 1.0

server:
  port: 8000
management:
  endpoints:
      web:
        exposure:
          include: '*'
        base-path: /
  server:
    port: 8001
  info:
    build:
      enabled: true
    defaults:
      enabled: true
    git:
      enabled: true

# example swagger definitions
documentation:
  swagger:
    services:
      -
        name: My Pet Service
        url: http://petstore.swagger.io/v2/swagger.json
        version: 2.0
      -
        name: Pet Professional SERVICES
        url: http://petstore.swagger.io/v2/swagger.json
        version: 2.0
      -
        name: Hobby Pet Service
        url: http://petstore.swagger.io/v2/swagger.json
        version: 2.0
      -
        name: Food Service
        url: http://petstore.swagger.io/v2/swagger.json
        version: 2.0


springfox:
  documentation:
    swagger:
      v2:
       path: /v2/swagger.json

